### ISSUE TITLE
Action gets triggered when a track design is hovered over the map

### ISSUE THREAD

**Issue by Gymnasiast** [jbodner09/openrct2-waittime#1]
The plugin subscribes to the "ride create" event, but unfortunately that event also gets fired when a track design is hovered over the map, where it creates a temporary ride. This results in many "Can’t change operating mode...” messages.

While I haven’t tried it myself (it was reported to me by a user), you could perhaps check the flags and see if they contain GAME_COMMAND_FLAG_NO_SPEND (= 1 << 5, or 32) - this is always passed when trying to place a track design, but not when placing a regular one (not even when money is disabled).

**Comment by jbodner09** [comment]
1 << 32 did it, so this is now fixed in the latest release (0.2).
